# --- config/_default/menus.yaml の全内容を以下に置き換え ---
main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers (準備中)
    url: '#'
    weight: 11
  - name: Talks (準備中)
    url: '#'
    weight: 12
  - name: News (準備中)
    url: '#'
    weight: 13
  - name: Experience (準備中)
    url: '#'
    weight: 20
  - name: Projects (準備中)
    url: '#'
    weight: 30
  - name: Teaching (準備中)
    url: '#'
    weight: 40
# --- ここまで ---