# --- config/_default/menus.yaml の修正案 ---
main:
  - name: Home
    url: / # ホーム（または #about）
    weight: 10
  - name: Papers (準備中)
    url: /publication/ # ← # から実際のパスに変更
    weight: 11
  - name: Talks (準備中)
    url: /event/ # ← # から実際のパスに変更
    weight: 12
  - name: News (準備中)
    url: /post/ # ← # から実際のパスに変更 (ブログ記事用)
    weight: 13
  - name: Experience (準備中)
    url: /experience/ # ← # から実際のパスに変更
    weight: 20
  - name: Projects (準備中)
    url: /project/ # ← # から実際のパスに変更
    weight: 30
  - name: Teaching (準備中)
    url: /teaching/ # ← # から実際のパスに変更
    weight: 40